adding a JAVA client to test the home-recipes services
kaushikchaubal/home-recipes pull request #5
Opened 2020-06-17 23:47 UTC by bhargavmehta01

2020-06-20 08:59 UTC, kaushikchaubal commented
I suggest to rename the branch from `app-client-java` to `test-client-java` to keep it consistent

2020-06-20 09:07 UTC, kaushikchaubal requested changes
Please update the two things  as mentioned in other comments:
1. Remove the duplicated proto folder and use the 'defs' folder which has all the proto definitions 
2. Rename the branch from app-client-java to test-client-java to keep it consistent

2020-06-20 09:07 UTC, kaushikchaubal commented on client/app-client-java/src/main/proto/google/api/annotations.proto
> +// Licensed under the Apache License, Version 2.0 (the "License");
Why is there a proto folder inside the client? Your client should pick up the protos from the defs folder. Please delete this folder and use the protos from the defs folder which  has all the definitions already

2020-06-24 02:10 UTC, bhargavmehta01 commented
- Removed the duplicated proto defs folder and now the project depends on the existing proto defs outside the project
- Renamed to 'test-client-java' for the consistency purpose

2020-06-25 07:44 UTC, merged

2020-06-25 07:44 UTC, kaushikchaubal commented
thanks for your contribution! 💯